const fs = require('fs');
const path = require('path');
const FormData = require('form-data');
const axios = require('axios');

// Pinata API Configuration
const PINATA_API_KEY = '0677124828904f06a14e';
const PINATA_API_URL = 'https://api.pinata.cloud/pinning/pinFileToIPFS';

async function uploadFileToPinata(filePath, metadata = {}) {
  const formData = new FormData();
  formData.append('file', fs.createReadStream(filePath));
  
  const pinataMetadata = JSON.stringify({
    name: metadata.name || path.basename(filePath),
    keyvalues: metadata.keyvalues || {}
  });
  formData.append('pinataMetadata', pinataMetadata);
  
  try {
    const response = await axios.post(PINATA_API_URL, formData, {
      maxBodyLength: Infinity,
      headers: {
        'Content-Type': `multipart/form-data; boundary=${formData._boundary}`,
        'pinata_api_key': PINATA_API_KEY,
        'pinata_secret_api_key': '' // Required but empty for this key type
      }
    });
    
    return response.data;
  } catch (error) {
    throw new Error(`Upload failed: ${error.response?.data?.message || error.message}`);
  }
}

async function uploadAllAssets() {
  console.log('🚀 Starting IPFS upload to Pinata...\n');
  console.log(`Using API Key: ${PINATA_API_KEY}\n`);
  
  const results = {
    mechs: {},
    animations: {},
    gateway: 'https://gateway.pinata.cloud/ipfs/'
  };
  
  // Upload mechs
  const mechsDir = path.join(__dirname, '../public/mechs');
  const mechFiles = fs.readdirSync(mechsDir).filter(f => f.endsWith('.glb'));
  
  console.log(`📁 Found ${mechFiles.length} mech files:\n`);
  
  for (const file of mechFiles) {
    const filePath = path.join(mechsDir, file);
    const fileSize = (fs.statSync(filePath).size / 1024 / 1024).toFixed(2);
    
    console.log(`⬆️  Uploading ${file} (${fileSize} MB)...`);
    
    try {
      const result = await uploadFileToPinata(filePath, {
        name: `MechForge - ${file}`,
        keyvalues: {
          type: 'mech',
          filename: file,
          project: 'MechForge',
          sizeMB: fileSize
        }
      });
      
      results.mechs[file] = {
        hash: result.IpfsHash,
        url: `https://gateway.pinata.cloud/ipfs/${result.IpfsHash}`,
        size: fileSize
      };
      
      console.log(`   ✅ Hash: ${result.IpfsHash}`);
      console.log(`   🔗 URL: https://gateway.pinata.cloud/ipfs/${result.IpfsHash}\n`);
    } catch (error) {
      console.error(`   ❌ Failed: ${error.message}\n`);
    }
  }
  
  // Upload animations
  const animationsDir = path.join(__dirname, '../public/animations');
  const animFolders = fs.readdirSync(animationsDir).filter(f => 
    fs.statSync(path.join(animationsDir, f)).isDirectory()
  );
  
  console.log(`\n📁 Found ${animFolders.length} animation folders:\n`);
  
  for (const folder of animFolders) {
    const folderPath = path.join(animationsDir, folder);
    const animFiles = fs.readdirSync(folderPath).filter(f => f.endsWith('.glb'));
    
    results.animations[folder] = {};
    
    console.log(`📂 ${folder}/ (${animFiles.length} files)`);
    
    for (const file of animFiles) {
      const filePath = path.join(folderPath, file);
      const fileSize = (fs.statSync(filePath).size / 1024 / 1024).toFixed(2);
      
      console.log(`   ⬆️  Uploading ${file} (${fileSize} MB)...`);
      
      try {
        const result = await uploadFileToPinata(filePath, {
          name: `MechForge - ${folder}/${file}`,
          keyvalues: {
            type: 'animation',
            mechType: folder,
            filename: file,
            project: 'MechForge',
            sizeMB: fileSize
          }
        });
        
        results.animations[folder][file] = {
          hash: result.IpfsHash,
          url: `https://gateway.pinata.cloud/ipfs/${result.IpfsHash}`,
          size: fileSize
        };
        
        console.log(`      ✅ Hash: ${result.IpfsHash}`);
      } catch (error) {
        console.error(`      ❌ Failed: ${error.message}`);
      }
    }
    console.log('');
  }
  
  // Save results
  const outputPath = path.join(__dirname, 'ipfs-hashes.json');
  fs.writeFileSync(outputPath, JSON.stringify(results, null, 2));
  
  // Also create a JS config file
  const jsConfig = generateJSConfig(results);
  const jsOutputPath = path.join(__dirname, '../src/config/ipfs.js');
  fs.writeFileSync(jsOutputPath, jsConfig);
  
  console.log('📄 Results saved to:');
  console.log(`   - ${outputPath}`);
  console.log(`   - ${jsOutputPath}\n`);
  
  printSummary(results);
  
  return results;
}

function generateJSConfig(results) {
  return `// IPFS Configuration for MechForge 3D Assets
// Auto-generated by upload-to-ipfs.js
// Gateway: https://gateway.pinata.cloud/ipfs/

export const IPFS_GATEWAY = 'https://gateway.pinata.cloud/ipfs/';

export const MECH_MODELS_IPFS = {
  1: '${results.mechs['omega_textured.glb']?.url || results.mechs[Object.keys(results.mechs).find(k => k.includes('omega'))]?.url || ''}', // Assault
  2: '${results.mechs['vanguard_textured.glb']?.url || results.mechs[Object.keys(results.mechs).find(k => k.includes('vanguard'))]?.url || ''}', // Tank
  3: '${results.mechs['scout_textured.glb']?.url || results.mechs[Object.keys(results.mechs).find(k => k.includes('scout'))]?.url || ''}', // Scout
  4: '${results.mechs['striker_textured.glb']?.url || results.mechs[Object.keys(results.mechs).find(k => k.includes('striker'))]?.url || ''}', // Sniper
  5: '${results.mechs['striker_textured.glb']?.url || results.mechs[Object.keys(results.mechs).find(k => k.includes('striker'))]?.url || ''}', // Support
};

export const MECH_ANIMATIONS_IPFS = {
  1: { // Omega/Assault
    idle: '${results.animations.omega?.['omega_idle_pose.glb']?.url || ''}',
    attack: '${results.animations.omega?.['omega_ultimate.glb']?.url || ''}',
    entrance: '${results.animations.omega?.['omega_entrance.glb']?.url || ''}',
  },
  2: { // Vanguard/Tank
    idle: '${results.animations.vanguard?.['vanguard_idle.glb']?.url || ''}',
    attack: '${results.animations.vanguard?.['vanguard_stomp.glb']?.url || ''}',
    defense: '${results.animations.vanguard?.['vanguard_defense.glb']?.url || ''}',
  },
  4: { // Striker/Sniper
    idle: '${results.animations.striker?.['striker_combat.glb']?.url || ''}',
    attack: '${results.animations.striker?.['striker_attack.glb']?.url || ''}',
    victory: '${results.animations.striker?.['striker_victory.glb']?.url || ''}',
  },
};

// Fallback to local paths if IPFS fails
export const getMechModelUrl = (mechType) => {
  return MECH_MODELS_IPFS[mechType] || \`/mechs/\${getMechFileName(mechType)}\`;
};

function getMechFileName(mechType) {
  const files = {
    1: 'omega_textured.glb',
    2: 'vanguard_textured.glb',
    3: 'scout_textured.glb',
    4: 'striker_textured.glb',
    5: 'striker_textured.glb',
  };
  return files[mechType] || files[1];
}
`;
}

function printSummary(results) {
  console.log('='.repeat(60));
  console.log('🎉 IPFS UPLOAD COMPLETE!');
  console.log('='.repeat(60));
  console.log('\n📊 Summary:');
  console.log(`   Mechs uploaded: ${Object.keys(results.mechs).length}`);
  console.log(`   Animation folders: ${Object.keys(results.animations).length}`);
  console.log(`\n🔗 Gateway: ${results.gateway}`);
  console.log('\n📝 Update Mech3DViewer.jsx with these IPFS URLs for reliable loading!');
  console.log('='.repeat(60));
}

// Check if axios and form-data are installed
async function checkDependencies() {
  try {
    require('axios');
    require('form-data');
  } catch (e) {
    console.log('Installing required dependencies...');
    const { execSync } = require('child_process');
    execSync('npm install axios form-data', { stdio: 'inherit', cwd: path.join(__dirname, '..') });
    console.log('Dependencies installed!\n');
  }
}

// Main execution
checkDependencies().then(() => {
  uploadAllAssets().catch(error => {
    console.error('❌ Upload failed:', error.message);
    process.exit(1);
  });
});
